shallow_clone: true

version: 1.0.{build}

os:
  - Visual Studio 2015

environment:
  matrix:
  - toolset: vs2015

platform:
  - Win32
  - x64

configuration:
  - debug
  - release

artifacts:
  - path: fts_remote_console_windows.zip
    name: to_publish

build:
  verbosity: minimal
  project: ./projects/$(toolset)/fts_console.sln

after_build:
  - ps: IF ($env:platform -eq "Win32") {$env:makeplatform = "x32"} ELSE ($env:makeplatform = $env:platform)
  - 7z a fts_remote_console_windows.zip "projects\%toolset%\bin\%makeplatform%_%configuration%\example_game" "projects\%toolset%\bin\%makeplatform%_%configuration%\fts_remote_console"


